# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.0
      with:
        version: 12

    - name: Installing Rimraf
      run: npm install rimraf

    - name: Installing Grunt CLI
      run: npm install -g grunt-cli

    - name: Installing Grunt
      run: npm install grunt

    - name: Installing Grunt SaSS
      run: npm install grunt-sass

    - name: INstalling Grunt Time
      run: npm install time-grunt

    - name: Installing GRUNT Jit
      run: npm install jit-grunt

    - name: Installing grunt-contrib-watch
      run: npm install grunt-contrib-watch

    - name: Installing grunt-browser-sync
      run: npm install grunt-browser-sync

    - name: Installing grunt-contrib-copy
      run: npm install grunt-contrib-copy

    - name: Installing grunt-contrib-clean
      run: npm install grunt-contrib-clean

    - name: Installing ImageMin
      run: npm install grunt-contrib-imagemin

    - name: Installing grunt-contrib-concat
      run: npm install grunt-contrib-concat

    - name: Installing grunt-contrib-cssmin
      run: npm install grunt-contrib-cssmin

    - name: Installing Grunt html min
      run: npm install grunt-contrib-htmlmin

    - name: Installing grunt-contrib-uglify
      run: npm install grunt-contrib-uglify

    - name: Installing grunt-filerev
      run: npm install grunt-filerev

    - name: Installing Grunt usemin
      run: npm install grunt-usemin
    

    - name: Creating build
      run: grunt build 
      
    - name: installing surge
      run: npm install -g surge
    
    - name: deploying on surge
      run: surge ./dist khatri-bootstrap4.surge.sh --token ${{ secrets.SURGE_TOKEN }}
